apiVersion: v1
kind: Service
metadata:
  name: snmp-exporter
  namespace: {{ .Values.namespace }}
  labels:
    app: snmp-exporter
    prometheus: main
spec:
  selector:
    app: snmp-exporter
  ports:
    - name: http
      port: 9116
      targetPort: 9116
