apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: egress-test
spec:
  selectors:
  - podSelector:
      matchLabels:
        app: tester
    namespaceSelector:
      matchLabels:
        name: test-tools
  egressGateway:
    nodeSelector:
      matchLabels:
        kubernetes.io/hostname: k8s-worker1
    egressIP: 10.0.200.2
  destinationCIDRs:
  - 0.0.0.0/0
