apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: istio
spec:
  version: 2
  enabled: true
  settings:
   outboundTrafficPolicyMode: RegistryOnly
   dataPlane:  
     trafficRedirectionSetupMode: CNIPlugin

